### DISCUSSION TITLE
systemd

### DISCUSSION THREAD

**Discussion by spham** [ansible-community/molecule-plugins#28] [docker] [answered]
Hi

for any image with systemd in molecule, when build with both config ( example in [molecule doc](https://molecule.readthedocs.io/en/latest/examples.html#systemd-container) 

on molecule login, i have this 
```
[root@rocky8 /]# systemctl
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
[root@rocky8 /]# exit
exit
```

is a bug or missing configuration ?

Here the config
```
# molecule.yml find in molecule doc
platforms:
  # - name: centos7
  #   image: milcom/centos7-systemd
  - name: rocky8
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
```

or rocky

```
# molecule.yml with rocky os
platforms:
  # - name: centos7
  #   image: milcom/centos7-systemd
  - name: rocky8
    image: rockylinux:8.6
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
```

ansible --version on Ubuntu 20.04 WSL2
```
ansible [core 2.13.4]
  config file = /home/spham/monprojetmoleculeavecdocker/ansible.cfg
  configured module search path = ['/home/spham/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/spham/v/lib/python3.8/site-packages/ansible
  ansible collection location = /home/spham/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/spham/v/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```
