### ISSUE TITLE
Docker plugin does not expand variable for "privileged"

### ISSUE THREAD

**Issue by LorenzoBettini** [ansible-community/molecule-plugins#104]
I'd like to pass a variable for the `privileged` part e.g.,

```yaml
platforms:
  - name: arch-instance
    image: arch-ansible
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    dockerfile: ../docker/Dockerfile
    build_image: true
...
    privileged: ${DOCKER_PRIVILEGED:-False}
```

During `TASK [Discover local Docker images]` the variable seems to be expanded correctly:

```
TASK [Discover local Docker images] ********************************************
ok: [localhost] => (item={'diff': [], '... 'platform': 'linux/amd64', 'privileged': False, ...
```

But then it fails later:

```
TASK [Wait for instance(s) creation to complete] *******************************
failed: ...
"msg": "argument 'privileged' is of type <class 'str'> and we were unable to convert to bool:
The value '${DOCKER_PRIVILEGED:-False}' is not a valid boolean. 
Valid booleans include: 'on', 'yes', 1, 0, '0', 'false', 'no', '1', 'f', 'off', 'y', 'true', 't', 'n'"...
```
