### ISSUE TITLE
Support to define multiple platforms 

### ISSUE THREAD

**Issue by wenesak** [ansible-community/molecule-plugins#13]
when initializing a new scenario for the azure driver a create.yml is created inside the newly created scenario

when looking at the  create.yml  the task to create the molecule instance has a CentOs hard-coded instance into the task, my request is:  can the template that creates this create.yml be updated to take all the values from the molecule_yml.platforms?, that way we don't have to manually update the  create.yml and just provide all the platforms specifics in the platforms section of the  molecule.yml

here is the task for the Create molecule instance(s) (taken from the auto-created create.yml)

```yaml
- name: Create molecule instance(s)
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ item.name }}"
        vm_size: Standard_A0
        admin_username: "{{ ssh_user }}"
        public_ip_allocation_method: Dynamic
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{ ssh_user }}/.ssh/authorized_keys"
            key_data: "{{ key_pair.ssh_public_key }}"
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.4'
          version: latest
      register: server
      with_items: "{{ molecule_yml.platforms }}"
      async: 7200
      poll: 0
```
