### ISSUE TITLE
EC2 driver volumes parameter does not validate against Molecule schema.

### ISSUE THREAD

**Issue by isuftin** [ansible-community/molecule-plugins#140]
In the platform definition of the EC2 driver, the expected type for the `volumes` parameter is a list of dict - https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/schemas/molecule.json

The Molecule schema definition for volumes expects a list of string - https://github.com/ansible-community/molecule/blob/main/src/molecule/data/molecule.json#L263-L268

As such, molecule errors out when attempting to create instances when `volumes` is defined in the platform param

An example of what a config for this might look like:

```yaml
volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 16
          delete_on_termination: true
```
