### ISSUE TITLE
SSH into EC2 instance fails with permission error

### ISSUE THREAD

**Issue by nandac** [ansible-community/molecule-plugins#152]
Dear Folks,

I am new to molecule and I am trying my hand at using the ec2 driver plugin.

I am able to create the EC2 instance and the required security group but have not been able to successfully login into the machine.

I keep getting the following error message when running `molecule create`.
```fatal: [molecule-instance]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Waiting on browser...\nBrowser step completed successfully.\nerror: Could not resolve: REDACTED: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).", "unreachable": true}```

I have only made minimal customizations such as disabling the creation of a public IP so that I may use a private IP instead. 

I have pasted the settings I have in my `molecule.yml` file below:

```yaml
---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: molecule-instance
    assign_public_ip: false
    connection_options:
      ansible_python_interpereter: /usr/bin/python
    image_name: "<REDACTED>"
    image_owner: ["<REDACTED>"]
    instance_type: t3.micro
    region: "<REDACTED>"
    ssh_user: ec2-user
    vpc_id: "<REDACTED>"
    vpc_subnet_id: "<REDACTED>"
    tags:
      Name: molecule-instance
provisioner:
  name: ansible
verifier:
  name: ansible
```

I know that this issue probably relates more to the Linux AMI I am using which is a slightly customized version of Amazon Linux 2 but I hope you may be able to shed some light.

I tried both the `ec2` and `cloud-init` for the `key_inject_methods` field but the SSH login does not work.

I look forward to your reply.

Many thanks.

**Comment by zhan9san** [comment]
@nandac 

Would you mind providing more detailed log of `molecule create`?

**Comment by nandac** [comment]
@ rdoshi1 I just assigned a public IP to the instance as far as I can remember.

This is my current `molecule.yml` setup, which works for me, but YMMV:

```yaml
---
dependency:
  name: galaxy
  requirements-file: requirements.yml
driver:
  name: ec2
platforms:
  - name: molecule-instance
    assign_public_ip: true
    aws_profile: <REDACTED>
    image_name: al2023-ami-2023.*-kernel-6.1-x86_64
    image_owner:
      - amazon
    instance_type: t3.medium
    region: us-west-2
    ssh_user: ec2-user
    security_group_rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: <REDACTED>
    vpc_id: <REDACTED>
    vpc_subnet_id: <REDACTED>
    tags:
      Name: molecule-instance
provisioner:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
```
