### ISSUE TITLE
23.4.1: box_url templating broken

### ISSUE THREAD

**Issue by yviel-de** [ansible-community/molecule-plugins#171]
Using `molecule-plugins` version `23.4.1` installed via `pipenv`, the templating of the `box_url` parameter is broken.

*How is it broken?*
It sets up `&#34;` control characters instead of double-quotes inside the Vagrantfile.

*Example Configuration*
```
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
platforms:
  - name: my-box
    box: my-box
    box_url: SOMESTRING
```

While all the other options get templated out OK, the `box_url` does not.
In the Vagrantfile that gets templated out, it shows up as `c.vm.box_url = &#34;SOMESTRING&#34;`, instead of `c.vm.box_url = "SOMESTRING"`, therefore creating a syntax error in the templated-out Vagrantfile.
