### ISSUE TITLE
Driver vagrant does not provide a schema

### ISSUE THREAD

**Issue by OGrigorios** [ansible-community/molecule-plugins#175]
I am currently facing the issue of wanting to run molecule with vagrant+libvirt.
I have verified that I can create virtual machines with vagrant+libvirt via vagrant-cli.
This perhaps leads to the error of:
```
TASK [Gather system info] ******************************************************
fatal: [test-wg-debianbull]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname test-wg-debianbull: Name or service not known", "
unreachable": true}
```

My molecule.yml:
```
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 192
      cpus: 2
platforms:
  - name: test-debianbull
    box: debian/bullseye64
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.10
provisioner:
  name: ansible
verifier:
  name: ansible
```

And my converge.yml 
```
---
- name: Converge
  hosts: all
  become: true
  remote_user: vagrant
  tasks:
    - name: "Include g7s.unbound"
      ansible.builtin.include_role:
        name: "g7s.unbound"
```

And the output from `molecule --version`

```
❯ molecule --version
molecule 5.1.0 using python 3.11
    ansible:2.15.1
    azure:23.4.1 from molecule_plugins
    containers:23.4.1 from molecule_plugins requiring collections: ansible.posix>=1.3.0 community.docker>=1.9.1 containers.podman>=1.8.1
    delegated:5.1.0 from molecule
    docker:23.4.1 from molecule_plugins requiring collections: community.docker>=3.0.2 ansible.posix>=1.4.0
    ec2:23.4.1 from molecule_plugins
    gce:23.4.1 from molecule_plugins requiring collections: google.cloud>=1.0.2 community.crypto>=1.8.0
    podman:23.4.1 from molecule_plugins requiring collections: containers.podman>=1.7.0 ansible.posix>=1.3.0
    vagrant:23.4.1 from molecule_plugins

```

I would appreciate any indicators of what might be wrong here. There was a similar [issue](https://github.com/ansible-community/molecule/issues/901) in 2017, but that did not help me.
