### ISSUE TITLE
Podman: build compatible Ansible image task don't use custom podman executable

### ISSUE THREAD

**Issue by ghoudmon** [ansible-community/molecule-plugins#253]
### Description

Podman driver allows to customize the podman executable path. This custom path is passed to all `containers.podman` modules, except for the task `Build an Ansible compatible image`.

### Current behavior

```yaml
    - name: Build an Ansible compatible image # noqa: no-handler
      containers.podman.podman_image:
        build:
          extra_args: >-
            {% if item.item.buildargs is defined %}{% for i, k in item.item.buildargs.items() %}--build-arg={{ i }}={{ k }}{% endfor %}{% endif %}
            {% if item.item.pull is defined %}--pull={{ item.item.pull }}{% endif %}
          file: "{{ item.dest }}"
        name: "molecule_local/{{ item.item.image }}"
        path: "{{ molecule_scenario_directory }}"
        pull: "{{ item.item.pull | default(omit) }}"
      loop: "{{ platforms.results }}"
```

### Expected behavior

```yaml
    - name: Build an Ansible compatible image # noqa: no-handler
      containers.podman.podman_image:
        executable: "{{ podman_exec }}"
        build:
          extra_args: >-
            {% if item.item.buildargs is defined %}{% for i, k in item.item.buildargs.items() %}--build-arg={{ i }}={{ k }}{% endfor %}{% endif %}
            {% if item.item.pull is defined %}--pull={{ item.item.pull }}{% endif %}
          file: "{{ item.dest }}"
        name: "molecule_local/{{ item.item.image }}"
        path: "{{ molecule_scenario_directory }}"
        pull: "{{ item.item.pull | default(omit) }}"
      loop: "{{ platforms.results }}"
```
