### ISSUE TITLE
Vagrant: excessive whitespace in Vagrantfile

### ISSUE THREAD

**Issue by dinadins** [ansible-community/molecule-plugins#276]
When running `molecule` with the Vagrant driver a Vagrantfile is produced in `~/.cache/molecule/[...]/default/Vagrantfile`. This can be very useful when troubleshooting. Unfortunately, this file has very many blank lines and the indentation is not consistent, making it hard to read.

It would be helpful to have this compacted and easier to read.

Example:

molecule.yml:
```
driver:
  name: vagrant
platforms:
  - name: instance-1
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8080"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    config_options:
      synced_folder: True
    box: debian/jessie64
    memory: 1024
    cpus: 1
    provider_options:
      gui: True
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--cpuexecutioncap', '50']"
    provider_override_args:
      - "vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"
    provision: True
```

Vagrantfile:

```
# Ansible managed

Vagrant.configure('2') do |config|
  if Vagrant.has_plugin?('vagrant-cachier')
    
    config.cache.scope = 'machine'
    
  end


  config.vm.define "instance-1" do |c|
    ##
    # Box definition
    ##
    c.vm.box = "debian/jessie64"





    ##
    # Config options
    ##
    

    
    
    
    c.ssh.insert_key = true
    

    
    c.vm.hostname = "instance-1"
    

    ##
    # Network
    ##
    
    c.vm.network "private_network", auto_config: true, type: "dhcp"
    

    ##
    # instance_raw_config_args
    ##
    c.vm.network 'forwarded_port', guest: 80, host: 8080
    

    ##
    # Provider
    ##
    c.vm.provider "virtualbox" do |virtualbox, override|
      
      virtualbox.memory = 1024
      virtualbox.cpus = 1
      

      
      virtualbox.gui = true
      

      
        
      virtualbox.customize ['modifyvm', :id, '--cpuexecutioncap', '50']
        
      

      
        override.vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'
        
      

      
      
      virtualbox.linked_clone = true
      
      
      
    end
  end

end
```
