### ISSUE TITLE
No networking with libvirt > 10.3.0 and Vagrant driver + libvirt provider

### ISSUE THREAD

**Issue by githubixx** [ansible-community/molecule-plugins#285]
I'm not sure if I'm in the right place here :wink: But it looks like that it might be an issue with Molecule vagrant plugin. I'm on Archlinux. Currently the following components are installed:

Kernel: `6.12.1`
Vagrant: `2.4.2`
python-vagrant: `1.1.0`
libvirt: `10.3.0 (latest available version 10.9.0)`

```bash
vagrant plugin list
vagrant-libvirt (0.12.3.pre.18, global)
```

I'm maintaining various Ansible roles like

https://github.com/githubixx/ansible-role-wireguard/blob/master/molecule/default/molecule.yml
https://github.com/githubixx/ansible-role-containerd/blob/master/molecule/default/molecule.yml

To test my roles I'm using Molecule and the `vagrant` driver with `libvirt` provider. E.g.:

```yaml
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-cd-ubuntu2004-base
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    groups:
      - ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.10
  - name: test-cd-ubuntu2204-base
    box: alvistack/ubuntu-22.04
    memory: 2048
    cpus: 2
    groups:
      - ubuntu
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.20
```

This worked fine all the times. But since `libvirt` 10.4.0 and newer I can't get the network of the virtual machines running anymore. I was hoping that the problem will be fixed with newer libvirt versions but sadly with libvirt 10.9.0 the issue is still there.

With libvirt 10.3.0 `molecule converge` runs just fine. But with libvirt >= 10.4.0 - no luck. All the other components are the same and it also doesn't depend on the Linux OS used for the VMs. So if I run `molecule converge` it looks like this:

```bash
WARNING  Driver vagrant does not provide a schema.
INFO     default scenario test matrix: dependency, create, prepare, converge
INFO     Performing prerun with role_name_check=0...
INFO     Running default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > create

PLAY [Create] ******************************************************************

TASK [Create molecule instance(s)] *********************************************
```

The VMs start like usual and I can see them in the `virt-manager` UI:

![libvirt](https://github.com/user-attachments/assets/55127a0b-e297-4558-8676-256932d79157)

But then nothing happens anymore for quite a while. If I then open a VM via `virt-manager` to see the console output it looks like this (Ubuntu 24.04.1 in this case):

![ubuntu24_startup](https://github.com/user-attachments/assets/42109a56-2bf8-43d1-ad06-44e4b4623693)

So the whole startup is obviously waiting for the network. After some time the startup continues but if you login via `virt-manager` and run `ip addr` there is no networking configured (well at least no IP addresses):

![ubuntu24_ip_addr](https://github.com/user-attachments/assets/da0a27d9-ee2a-4753-9cfc-2de103b2798e)

Sooner or later I get `fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["/usr/bin/vagrant", "up", "--no-provision"], "msg": "Failed to start the VM(s): See log file '/home/ausername/.cache/molecule/githubixx.containerd/default/vagrant.err`. The `vagrant.err` looks like this:

[vagrant.err.txt](https://github.com/user-attachments/files/17951782/vagrant.err.txt)

and the created VMs are shutting down.

So maybe someone has an idea. That would be nice :smiley: Downgrading to libvirt 10.3.0 works as mentioned but I guess sooner or later that will also stop to work because of whatever dependencies and I'd really like to keep my setup. Thx!
