### ISSUE TITLE
Mitogen along with Podman and ansible getting stuck in waiting for container creating

### ISSUE THREAD

**Issue by sunilsankar** [ansible-community/molecule-plugins#286]
When I enable mitogen in molecule.cfg 
```
config_options:
    defaults:
        strategy_plugins: >-
         /usr/local/lib/python3.9/site-packages/ansible_mitogen/plugins/strategy
        strategy: "mitogen"
```
. It gets stuck in container creating. But when I disable mitogen it works. The following versions are installed
```
ansible==8.7.0
ansible-compat==24.10.0
ansible-core==2.15.13
ansible-lint==6.22.2
molecule==6.0.3
molecule-plugins==23.5.3
mitogen @ file:///home/xxxx/mitogen-0.3.19.tar.gz
```
There are no errors in the log
molecule.yml
```
---
scenario:
  name: "rhel9"

driver:
  name: "podman"

dependency:
  name: "galaxy"
  options:
    role-file: "molecule/shared/requirements.yml"
provisioner:
  name: "ansible"
  playbooks:
    converge: "../shared/playbook.yml"
    prepare: "../shared/prepare.yml"
  config_options:
    #defaults:
     #  strategy_plugins: >-
       # /usr/local/lib/python3.9/site-packages/ansible_mitogen/plugins/strategy
       # strategy: "mitogen"
  inventory:
    host_vars:
      rac-instance-${BUILD_BUILDID:-1001}:
        ansible_python_interpreter: "/usr/bin/python3.9"
        rs_rac_version: "1.61a"
        eap_version: "7.3.3"
 
        # General settings
        theme: "rac"
        user: "rac"
        user_id: 10000
        group: "rac"
        group_id: 10000
        rac_np_group: "rac"

        base_path: "/appl/{{ theme }}"

        rac_eap_admin_password: "password"
        rac_eap_vault_password: "password"

        # Databases required
        molecule_database_schemas:
          - RSS
          - RSI
          - RSW

        # Molecule generated database users
        rac_db_app_rss_user: >-
          {{ lookup('file', molecule_ephemeral_directory ~ '/molecule_db_user_rss_username') }}
        rac_db_app_rss_password: >-
          {{ lookup('file', molecule_ephemeral_directory ~ '/molecule_db_user_rss_password') }}
        rac_db_app_rsi_user: >-
          {{ lookup('file', molecule_ephemeral_directory ~ '/molecule_db_user_rsi_username') }}
        rac_db_app_rsi_password: >-
          {{ lookup('file', molecule_ephemeral_directory ~ '/molecule_db_user_rsi_password') }}
        rac_db_app_rsw_user: >-
          {{ lookup('file', molecule_ephemeral_directory ~ '/molecule_db_user_rsw_username') }}
        rac_db_app_rsw_password: >-
          {{ lookup('file', molecule_ephemeral_directory ~ '/molecule_db_user_rsw_password') }}

        rac_db_owner_rsw_user: >-
          {{ lookup('file', molecule_ephemeral_directory ~ '/molecule_db_owner_rsw_username') }}
        rac_db_owner_rsw_password: >-
          {{ lookup('file', molecule_ephemeral_directory ~ '/molecule_db_owner_rsw_password') }}

        rac_db_rss_connect: "jdbc:oracle:thin:@{{ database_name }}"
        oracle_client_systemwide: true
        rac_oracle_client_path: "/usr/lib/oracle_client"
        # Database settings for pipeline
        database_engine: "Oracle"
        database_host: "${DATABASE_HOST:-$HOSTNAME}"
        database_port: "1521"
        database_service_name: "XEPDB1"
        database_name: >-
          (DESCRIPTION=
          (ADDRESS=
          (PROTOCOL=tcp)
          (HOST={{ database_host }})
          (PORT={{ database_port }}))
          (CONNECT_DATA=(SERVICE_NAME={{ database_service_name }})))

        # Certgen related
        rac_certgen_selfsigned: true
        rac_certgen_passphrase: "passphrase"
        rac_dns_name: "test-r4d-sandbox.dev.xxx.nl"
        rac_certificates_path: "/appl/{{ theme }}/certificates"
        # EAP Metaspace
        eap_min_metaspace_size: "96m"
        eap_max_metaspace_size: "512m"
        # RAC user pool size
        min_pool_size: "1"
        max_pool_size: "50"
        rsi_min_pool_size: "undefined"
        rsi_max_pool_size: "undefined"
        rsw_min_pool_size: "2"
        rsw_max_pool_size: "20"
        pool_prefill: true
        rsi_pool_prefill: false
        rsw_pool_prefill: true
        rac_security_authentication_method: "BUILTIN"

verifier:
  name: "testinfra"
  options:
    junitxml: "TEST-testinfra.xml"

platforms:
  - name: "rac-instance-${BUILD_BUILDID:-1001}"
    hostname: "rac-instance-${BUILD_BUILDID:-1001}.eu.xxx.com"
    image: "test.xxx.nl/rhel9-init"
    pre_build_image: true
    pull: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    command: "/usr/sbin/init"
    groups:
      - ${ENV_GROUP:-xx_sandbox}
      - rac
      - dec
      - dbl
      - prj
      - beb
      - inspec
    networks:
      - name: "rac-molecule-${BUILD_BUILDID:-1001}"

```
Not sure how to debug this issue
