### ISSUE TITLE
molecule-vagrant does not run `box remove` on destroy.

### ISSUE THREAD

**Issue by r-pufky** [ansible-community/molecule-plugins#290]
To idemptotently destroy a vagrant VM, you must run `vagrant box remove box/name` otherwise remenants of the VM will remain when re-running molecule create steps, leading hard to debug errors.

Here's the vagrant documentation specifying as such: https://developer.hashicorp.com/vagrant/docs/cli/destroy

On molecule destroy, vagrant should also call `vagrant box remove box/name` to ensure idempotent testing conditions.

**Comment by apatard** [comment]
_well, this problem has been there for ages, afair._

From a **quick** thought: 
- If one wants to make the plugin remove the box, the plugin would have to know it was not already there or something like that,
- for one task, it's fine but if there are several tests with the same box on the system, downloading each time the box
  would be "annoying" and slowing things a lot.

**Comment by carlosaya** [comment]
> [@carlosaya](https://github.com/carlosaya), could you provide more info regarding this?
> 
> when I run `destroy` or the test sequence, my boxes end up in a `not created` state.
> 
> ~/.cache/molecule/ansible-role-template/default$ vagrant status | grep noble
> noble                     not created (virtualbox)

hi @konstruktoid sorry for the slow reply - time zones!  plus I have been fighting firewall demons between WSL and Windows  😓 

here is `vagrant status` before/after running `molecule destroy`:

```
$ vagrant status
Current machine states:

instance                  running (virtualbox)

$ vagrant status
Current machine states:

instance                  not created (virtualbox)
```

The machine remains in virtualbox though:

<img width="1413" height="873" alt="Image" src="https://github.com/user-attachments/assets/9e0f4724-dd43-4bf9-8370-647397078bad" />

If I run `molecule create` again at this point then a new VM is created in VirtualBox.  Thats good and is what I want, but I still wonder what the value is in leaving behind a VM when I run `molecule destroy`?  In this case, even a VM that I did absolutely nothing with is still consuming almost half a GB of space.  If someone was doing a bunch of testing then they would chew through disk space pretty quickly.

I worked around this by creating a custom destroy.yml which runs `vagrant destroy` to completely delete the VM.  I feel like this should be the default behavior, but open to hearing why it is the way it is.

```
---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Destroy molecule instance(s)
      ansible.builtin.command:
        cmd: vagrant destroy -f
      args:
        chdir: "{{ molecule_ephemeral_directory }}"
      register: server
      changed_when: server.rc == 0
      check_mode: false
      no_log: false

    # Mandatory configuration for Molecule to function.
    - name: Dump instance config
      ansible.builtin.copy:
        content: "{}"
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
```
