### ISSUE TITLE
Podman driver doesn't honor "podman_extra_args" at creation/destruction

### ISSUE THREAD

**Issue by J-PC** [ansible-community/molecule-plugins#305]
When using the podman driver with `podman-remote` as executable (variable MOLECULE_PODMAN_EXECUTABLE=podman-remote) with many connections registered, I'd like to choose which connection to use and not necessarily the default one.

I looked into the podman driver documentation and it's specified that the create/destroy playbooks follow the podman ansible connector specification, so I decided to set the connection with the `podman_extra_args` parameter in the molecule.yaml :

```
provisioner:
  name: ansible
  config_options:
    defaults:
      podman_extra_args: --connection fake_connection
```

The problem is that the parameter is not honored during the creation but starts to be honored during the prepare phase and probably is not honored during the destruction phase either.
One quick way to test the problem is to set a connection that doesn't exist.
