### ISSUE TITLE
 Providing vpc_subnet_id, but  failing one get_default_subnet

### ISSUE THREAD

**Issue by natemarks** [ansible-community/molecule-plugins#46]
I think it's failing because my account has neither a default vpc nor a default subnet - even though I do provide a vpc id and subnet id

My molecule yaml looks like this (redacted IDs):
```
---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: instance
    image_id: ami-abc123abc123
    instance_type: t2.micro
    region: us-east-1
    vpc_id: vpc-abc123abc123
    vpc_subnet_id: subnet-abc123abc123
    tags:
      - Name: molecule_instance
provisioner:
  name: ansible
verifier:
  name: ansible

```
```
stderr_lines": [
    "Traceback (most recent call last):",
    "  File \"/Users/nmarks/.ansible/tmp/ansible-tmp-1639218466.1749592-46512-137934100112825/AnsiballZ_ec2_instance.py\", line 107, in <module>",
    "    _ansiballz_main()",
    "  File \"/Users/nmarks/.ansible/tmp/ansible-tmp-1639218466.1749592-46512-137934100112825/AnsiballZ_ec2_instance.py\", line 99, in _ansiballz_main",
    "    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)",
    "  File \"/Users/nmarks/.ansible/tmp/ansible-tmp-1639218466.1749592-46512-137934100112825/AnsiballZ_ec2_instance.py\", line 47, in invoke_module",
    "    runpy.run_module(mod_name='ansible_collections.amazon.aws.plugins.modules.ec2_instance', init_globals=dict(_module_fqn='ansible_collections.amazon.aws.plugins.modules.ec2_instance', _modlib_path=modlib_path),",
    "  File \"/Users/nmarks/.pyenv/versions/3.9.2/lib/python3.9/runpy.py\", line 210, in run_module",
    "    return _run_module_code(code, init_globals, run_name, mod_spec)",
    "  File \"/Users/nmarks/.pyenv/versions/3.9.2/lib/python3.9/runpy.py\", line 97, in _run_module_code",
    "    _run_code(code, mod_globals, init_globals,",
    "  File \"/Users/nmarks/.pyenv/versions/3.9.2/lib/python3.9/runpy.py\", line 87, in _run_code",
    "    exec(code, run_globals)",
    "  File \"/var/folders/72/cmp8x83n3js_spr_3hvvdgch0000gn/T/ansible_ec2_instance_payload_1wo209qr/ansible_ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_instance.py\", line 1910, in <module>",
    "  File \"/var/folders/72/cmp8x83n3js_spr_3hvvdgch0000gn/T/ansible_ec2_instance_payload_1wo209qr/ansible_ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_instance.py\", line 1886, in main",
    "  File \"/var/folders/72/cmp8x83n3js_spr_3hvvdgch0000gn/T/ansible_ec2_instance_payload_1wo209qr/ansible_ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_instance.py\", line 1794, in build_filters",
    "  File \"/var/folders/72/cmp8x83n3js_spr_3hvvdgch0000gn/T/ansible_ec2_instance_payload_1wo209qr/ansible_ec2_instance_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_instance.py\", line 1446, in get_default_subnet",
    "TypeError: 'NoneType' object is not subscriptable"
  ],
```
